import database from "./db.js";

export const createTables = async () => {
  await database.query(`CREATE TABLE IF NOT EXISTS users (id UUID DEFAULT gen_random_uuid() PRIMARY KEY, name VARCHAR(100) NOT NULL CHECK (char_length(name) >= 3), email VARCHAR(100) UNIQUE NOT NULL, password TEXT NOT NULL, role VARCHAR(10) DEFAULT 'User' CHECK (role IN ('User', 'Admin')), avatar JSONB DEFAULT NULL, reset_password_token TEXT DEFAULT NULL, reset_password_expire TIMESTAMP DEFAULT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);`);
  await database.query(`CREATE TABLE IF NOT EXISTS products (id UUID DEFAULT gen_random_uuid() PRIMARY KEY, name VARCHAR(255) NOT NULL, description TEXT NOT NULL, price DECIMAL(7,2) NOT NULL CHECK (price >= 0), category VARCHAR(100) NOT NULL, ratings DECIMAL(3,2) DEFAULT 0 CHECK (ratings BETWEEN 0 AND 5), images JSONB DEFAULT '[]'::JSONB, stock INT NOT NULL CHECK (stock >= 0), created_by UUID NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE CASCADE);`);
  await database.query(`CREATE TABLE IF NOT EXISTS reviews (id UUID DEFAULT gen_random_uuid() PRIMARY KEY, product_id UUID NOT NULL, user_id UUID NOT NULL, rating DECIMAL(3,2) NOT NULL CHECK (rating BETWEEN 0 AND 5), comment TEXT NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE, FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE);`);
  await database.query(`CREATE TABLE IF NOT EXISTS orders (id UUID DEFAULT gen_random_uuid() PRIMARY KEY, buyer_id UUID NOT NULL, total_price DECIMAL(10,2) NOT NULL CHECK (total_price >= 0), tax_price DECIMAL(10,2) NOT NULL DEFAULT 0, shipping_price DECIMAL(10,2) NOT NULL DEFAULT 0, order_status VARCHAR(20) DEFAULT 'Processing' CHECK (order_status IN ('Processing', 'Shipped', 'Delivered', 'Cancelled')), paid_at TIMESTAMP DEFAULT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (buyer_id) REFERENCES users(id) ON DELETE CASCADE);`);
  await database.query(`CREATE TABLE IF NOT EXISTS order_items (id UUID DEFAULT gen_random_uuid() PRIMARY KEY, order_id UUID NOT NULL, product_id UUID NOT NULL, quantity INT NOT NULL CHECK (quantity > 0), price DECIMAL(10,2) NOT NULL CHECK (price >= 0), image TEXT NOT NULL, title TEXT NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE, FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE);`);
  await database.query(`CREATE TABLE IF NOT EXISTS shipping_info (id UUID DEFAULT gen_random_uuid() PRIMARY KEY, order_id UUID NOT NULL UNIQUE, full_name VARCHAR(100) NOT NULL, state VARCHAR(100) NOT NULL, city VARCHAR(100) NOT NULL, country VARCHAR(100) NOT NULL, address TEXT NOT NULL, pincode VARCHAR(10) NOT NULL, phone VARCHAR(20) NOT NULL, FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE);`);
  await database.query(`CREATE TABLE IF NOT EXISTS payments (id UUID DEFAULT gen_random_uuid() PRIMARY KEY, order_id UUID NOT NULL UNIQUE, payment_type VARCHAR(20) NOT NULL CHECK (payment_type IN ('Online')), payment_status VARCHAR(20) NOT NULL CHECK (payment_status IN ('Paid', 'Pending', 'Failed')), payment_intent_id VARCHAR(255) UNIQUE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE);`);
  console.log("All tables created successfully");
};
